// components/comment-section.tsx
"use client";

import React, { useState, useEffect } from "react";
import IndividualComment from "./individual-comment";
import { CommentForm } from "./comment-form";
import { Comment } from "@/lib/types";

interface CommentSectionProps {
  postId: string;
}

// Mock function to simulate fetching comments
const fetchCommentsForBlog = async (postId: string): Promise<Comment[]> => {
    console.log(`Fetching comments for post ID: ${postId}`);
    // CORRECTED: The mock data now includes 'id' and matches the Comment type
    return [
        { id: "1", _id: "1", blogId: postId, authorName: "Alice", authorEmail: "alice@example.com", content: "This was an incredibly insightful read. Thank you!", createdAt: "2025-09-11" },
        { id: "3", _id: "3", blogId: postId, authorName: "Charlie", authorEmail: "charlie@example.com", content: "Looking forward to part 2 of this series!", createdAt: "2025-09-09" },
    ];
};

export function CommentSection({ postId }: CommentSectionProps) {
    const [comments, setComments] = useState<Comment[]>([]);
    const [loading, setLoading] = useState(false);
    
    useEffect(() => {
        const loadComments = async () => {
            const fetchedComments = await fetchCommentsForBlog(postId);
            setComments(fetchedComments);
        };
        loadComments();
    }, [postId]);

    const handleCommentSubmit = (commentData: { authorName: string; authorEmail: string; content: string }) => {
        console.log("New comment submitted:", commentData);
        // CORRECTED: The new comment now includes all required properties
        const newComment: Comment = {
            id: Math.random().toString(),
            _id: Math.random().toString(), // Typically generated by the database
            blogId: postId,
            createdAt: new Date().toISOString(),
            ...commentData
        };
        setComments(prevComments => [newComment, ...prevComments]);
    };

    return (
        <section className="py-8">
            <h2 className="text-2xl font-bold mb-6">Comments ({comments.length})</h2>
            <div className="space-y-6">
                {/* CORRECTED: The key now correctly uses 'comment.id' */}
                {comments.map(comment => (
                    <IndividualComment key={comment.id} comment={comment} />
                ))}
            </div>
            <hr className="my-8" />
            <CommentForm 
                blogId={postId}
                onSubmitComment={handleCommentSubmit}
                loading={loading}
            />
        </section>
    );
};